apiVersion: v1
kind: ConfigMap
metadata:
 name: coredns
 namespace: kube-system
data:
 Corefile: |
   .:53 {
       errors
       ready
       health
       kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
       }
       prometheus :9153
       forward . /etc/resolv.conf
       cache 10
       loop
       reload
       loadbalance
   }
   eastus.svc.cluster.local:53 {       # <---- Modify
       log
       errors
       ready
       cache 10
       forward . 20.0.0.43 20.0.0.87 52.186.45.255 {      # <---- Modify

       }
   }
   northeurope.svc.cluster.local:53 {       # <---- Modify
       log
       errors
       ready
       cache 10
       forward . 40.0.0.17 40.0.0.96 52.186.44.236 {      # <---- Modify

       }
   }
