apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"eastus.svc.cluster.local": ["20.62.188.192"], "northeurope.svc.cluster.local": ["20.62.188.180"]}
